<!DOCTYPE html>
<html lang="rus,en">
<head>
    <meta charset="UTF-8">
    <title>Fruits supply</title>
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/css/home.css">
</head>
<body>
<div class="wrapper">
    <label>Add new delivery</label>
    <a href="/addDelivery/chooseCompany">
        <button type="submit">Add delivery</button>
    </a>
    <label>Create a report</label>
    <a href="/chooseInfoForReport">
        <button type="submit">Create a report</button>
    </a>
    <label>Add supplier</label>
    <a href="/addSupplier">
        <button type="submit">Add supplier</button>
    </a>
    <label>Add product</label>
    <a href="/addProduct">
        <button type="submit">Add product</button>
    </a>
</div>
</body>
</html>