<!DOCTYPE html>
<html lang="rus,en">
<head>
    <meta charset="UTF-8">
    <title>Tic-Tac-Toe</title>
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/css/home.css">
</head>
<body>
<div class="wrapper">
    <h1 class="name">Tic-Tac-Toe</h1>
    <h2 class="text">This is a classic two-player strategy game that combines simple rules with deep tactical thinking.
        The game is played on a 3x3 grid where players take turns placing their marks: cross (X) or circle (O).
        The objective is to be the first to form a line of three identical marks horizontally, vertically, or diagonally.
        If all grid cells are filled without either player creating a line, the game ends in a draw.</h2>
    <a href="/registration">
        <button type="submit" class="registration">Register</button>
    </a>
    <a href="/auth">
        <button type="submit" class="logIn">Login</button>
    </a>
</div>
</body>
</html>