<!DOCTYPE html>
<html lang="rus,en">
<head>
    <meta charset="UTF-8">
    <title>Menu</title>
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/css/menu.css">
</head>

<body>
<a href="/newGameWithComputer">
    <button class="newGameWithComputer">New game with Ai</button>
</a>
<a href="/newGameWithHuman">
    <button class="newGameWithHuman">Create online game</button>
</a>
<a href="/chooseGameWithHuman">
    <button class="chooseGameWithHuman">Join online game</button>
</a>
<a href="/allGamesWithComputer">
    <button class="allGamesWithComputer">My games vs Ai</button>
</a>
<a href="/allGamesWithHuman">
    <button class="allGamesWithHuman">My online games</button>
</a>
<a href="/allEndedGames">
    <button class="allEndedGames">My ended games</button>
</a>
<a href="/scoreBoard">
    <button class="scoreBoard">Top players</button>
</a>
<a href="/profile">
    <button class="profile">My profile</button>
</a>
</body>
</html>