<!DOCTYPE html>
<html lang="rus,en">
<head>
    <meta charset="UTF-8">
    <title>Крестики нолики</title>
    <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/css/home.css">
</head>
<body>
<div class="wrapper">
    <h1 class="name">КРЕСТИКИ НОЛИКИ</h1>
    <h2 class="text">Это классическая стратегическая игра для двух игроков, которая сочетает в себе простоту правил и
        глубину тактического мышления. Игра ведется на поле 3x3, где каждый игрок по очереди ставит свой знак: крестик
        (X) или нолик (O). Цель игры — первым выстроить линию из трех своих знаков по горизонтали, вертикали или
        диагонали. Если все клетки поля заполнены, но ни один из игроков не смог создать линию, игра заканчивается
        ничьей.</h2>
    <a href="/registration">
        <button type="submit" class="registration">Зарегистрироваться</button>
    </a>
    <a href="/auth">
        <button type="submit" class="logIn">Войти</button>
    </a>
</div>
</body>
</html>