<!DOCTYPE html>
<html lang="rus,en">
<head>
    <meta charset="UTF-8">
    <title>Меню</title>
    <link rel="icon" href="images/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/css/menu.css">
</head>

<body>
<a href="/newGameWithComputer">
    <button class="newGameWithComputer">Играть с компьютером</button>
</a>
<a href="/newGameWithHuman">
    <button class="newGameWithHuman">Создать игру по сети</button>
</a>
<a href="/chooseGameWithHuman">
    <button class="chooseGameWithHuman">Подключиться к игре по сети</button>
</a>
<a href="/allGamesWithComputer">
    <button class="allGamesWithComputer">Мои игры с компьютером</button>
</a>
<a href="/allGamesWithHuman">
    <button class="allGamesWithHuman">Мои игры по сети</button>
</a>
<a href="/allEndedGames">
    <button class="allEndedGames">Завершенные игры</button>
</a>
<a href="/scoreBoard">
    <button class="scoreBoard">Таблица лидеров</button>
</a>
<a href="/profile">
    <button class="profile">Мой профиль</button>
</a>
</body>
</html>